sudo: required

language: java

before_install:
  - sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

script:
  - "mvn cobertura:cobertura" # Thanks to https://github.com/codecov/example-java-maven
  - mvn install
  - mvn test
  - mvn exec:java -Dexec.mainClass="me.henryfbp.generator.ResumeGeneratorHTML"
  - mvn exec:java -Dexec.mainClass="me.henryfbp.generator.ResumeGeneratorLaTeX"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "potato :-)"